//! The bounded log shown in the log panel.

/// Maximum number of lines kept in memory.
const MAX_LINES: usize = 20_000;

/// Severity of a log line, used for coloring.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LogKind {
    /// Normal engine output.
    Info,
    /// `[ERROR]` lines and standard error output.
    Error,
    /// Messages generated by the GUI itself.
    Gui,
    /// Final success message.
    Success,
}

/// One line in the log panel.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LogLine {
    /// Severity.
    pub kind: LogKind,
    /// Text without a trailing newline.
    pub text: String,
}

/// Log lines with a size limit; the oldest tenth is dropped when full.
#[derive(Debug, Clone, Default)]
pub struct LogBuffer {
    /// Stored lines, oldest first.
    lines: Vec<LogLine>,
}

impl LogBuffer {
    /// Appends a line, dropping the oldest lines when the buffer is full.
    pub fn push(&mut self, kind: LogKind, text: impl Into<String>) {
        if self.lines.len() >= MAX_LINES {
            self.lines.drain(..MAX_LINES / 10);
        }

        self.lines.push(LogLine {
            kind,
            text: text.into(),
        });
    }

    /// Removes all lines.
    pub fn clear(&mut self) {
        self.lines.clear();
    }

    /// All lines, oldest first.
    pub fn lines(&self) -> &[LogLine] {
        &self.lines
    }

    /// Joins every line with `\n`, for copying to the clipboard.
    pub fn to_text(&self) -> String {
        self.lines
            .iter()
            .map(|line| line.text.as_str())
            .collect::<Vec<_>>()
            .join("\n")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn drops_oldest_lines_when_full() {
        let mut log = LogBuffer::default();
        for i in 0..=MAX_LINES {
            log.push(LogKind::Info, i.to_string());
        }

        assert_eq!(log.lines().len(), MAX_LINES - MAX_LINES / 10 + 1);
        assert_eq!(log.lines()[0].text, (MAX_LINES / 10).to_string());
    }

    #[test]
    fn joins_lines_as_text() {
        let mut log = LogBuffer::default();
        log.push(LogKind::Info, "a");
        log.push(LogKind::Error, "b");
        assert_eq!(log.to_text(), "a\nb");
    }
}
